### ISSUE TITLE
How

### ISSUE THREAD

**Issue by CJDaBomb** [Fl3t/NitroGenerator#5]
how do you use this thing?

**Comment by Fijxu** [comment]
Clone the repo or download it as zip, open discord folder, open cmd in the folder, execute python and the name of the file with termination of .py

Linux: python3 (filename).py
Windows: py (filename).py

**Comment by BobusDev** [comment]
> Clone the repo or download it as zip, open discord folder, open cmd in the folder, execute python and the name of the file with termination of .py
> 
> Linux: python3 (filename).py
> Windows: py (filename).py

it gave me this error
`C:\Users\luqma\Downloads\nitrx\NitroGenerator-master\NitroGenerator-master\discord>py nitrogen.py
Traceback (most recent call last):
  File "C:\Users\luqma\Downloads\nitrx\NitroGenerator-master\NitroGenerator-master\discord\nitrogen.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by YTFlashplayz** [comment]
> > Clone the repo or download it as zip, open discord folder, open cmd in the folder, execute python and the name of the file with termination of .py
> > Linux: python3 (filename).py
> > Windows: py (filename).py
> 
> it gave me this error
> `C:\Users\luqma\Downloads\nitrx\NitroGenerator-master\NitroGenerator-master\discord>py nitrogen.py Traceback (most recent call last): File "C:\Users\luqma\Downloads\nitrx\NitroGenerator-master\NitroGenerator-master\discord\nitrogen.py", line 1, in <module> import requests ModuleNotFoundError: No module named 'requests'`

same here

**Comment by Fijxu** [comment]
> 
> 
> > Clone the repo or download it as zip, open discord folder, open cmd in the folder, execute python and the name of the file with termination of .py
> > Linux: python3 (filename).py
> > Windows: py (filename).py
> 
> it gave me this error
> `C:\Users\luqma\Downloads\nitrx\NitroGenerator-master\NitroGenerator-master\discord>py nitrogen.py Traceback (most recent call last): File "C:\Users\luqma\Downloads\nitrx\NitroGenerator-master\NitroGenerator-master\discord\nitrogen.py", line 1, in <module> import requests ModuleNotFoundError: No module named 'requests'`



> 
> 
> > > Clone the repo or download it as zip, open discord folder, open cmd in the folder, execute python and the name of the file with termination of .py
> > > Linux: python3 (filename).py
> > > Windows: py (filename).py
> > 
> > 
> > it gave me this error
> > `C:\Users\luqma\Downloads\nitrx\NitroGenerator-master\NitroGenerator-master\discord>py nitrogen.py Traceback (most recent call last): File "C:\Users\luqma\Downloads\nitrx\NitroGenerator-master\NitroGenerator-master\discord\nitrogen.py", line 1, in <module> import requests ModuleNotFoundError: No module named 'requests'`
> 
> same here

Ur 2, paste that in the console/terminal.

Windows: 
`pip install requests`

Linux:
`pip3 install requests`

Also u need a proxy list, u can download some of proxies in internet, then paste it in proxys.txt and execute the code

**Comment by tammymooms0909** [comment]
ooh ok ty, i alr got some proxylist with like 1k+ active, so , yea

**Comment by YNWho-0** [comment]
> ooh ok ty, i alr got some proxylist with like 1k+ active, so , yea

would you mind sharing it?

**Comment by lightning109** [comment]
it give me this error when i run it : 

> Error, Set Characters, Threads And List Proxys!!!
